### PR TITLE
[fix] styling

### PR DESCRIPTION
**Pull request by JoOkuma**
Hi. Just complementing the previous commit. It should be good to go now.
Not sure how it went through the pre-commit.

### CODE REVIEW

**Comment by JoOkuma** [comment]
Hi @alisterburt, just a reminder so you don't forget this PR.

**Comment by alisterburt** [comment]
thanks @JoOkuma and sorry for the slow turnaround here!

**Comment by alisterburt** [comment]
thanks @JoOkuma and sorry for the slow turnaround here!

**Comment by alisterburt** [comment]
thanks @JoOkuma and sorry for the slow turnaround here!

**Pull request merged**
